version: "3.5"

networks:
  openstates-network:
      name: openstates-network

volumes:
  openstates-postgres:
    name: openstates-postgres

services:
  django:
    build:
      context: .
      dockerfile: docker/uwsgi/Dockerfile
    volumes:
      - .:/code:z
    environment:
      - UMASK=0000
      # dev settings to reload python files when edited
      - UWSGI_PYTHON_AUTORELOAD=3
      - UWSGI_ENABLE_THREADS=1
      - DEBUG=True
      - SECRET_KEY
      - DATABASE_URL
      - CACHE_URL
      - RECAPTCHA_PUBLIC_KEY
      - RECAPTCHA_PRIVATE_KEY
    networks:
      - openstates-network

  nginx:
    build: docker/nginx
    ports:
      - "8000:80"
    depends_on:
      - django
    networks:
      - openstates-network

  # webpack:
  #   build: .
  #   command: ./docker/webpack-start.sh
  #   volumes:
  #     - .:/code
