version: "3.5"

services:
  django:
    build:
      context: .
      dockerfile: docker/uwsgi/Dockerfile
      args:
        UID: 1000
    volumes:
      - .:/code
    environment:
      # dev settings to reload python files when edited
      - UWSGI_PYTHON_AUTORELOAD=3
      - UWSGI_ENABLE_THREADS=1
      - DEBUG=True
      - SECRET_KEY
      - DATABASE_URL
      - CACHE_URL
      - RECAPTCHA_PUBLIC_KEY
      - RECAPTCHA_PRIVATE_KEY

  nginx:
    build: docker/nginx
    ports:
      - "8000:80"
    depends_on:
      - django

  # webpack:
  #   build: .
  #   command: ./docker/webpack-start.sh
  #   volumes:
  #     - .:/code
