name: Build and push Docker images
on:
  push:
    branches:
      - develop
    tags:
      - '*'
jobs:
  publish:
    steps:
      - uses: actions/checkout@v2
      - name: build cron docker image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: openstates/openstates.org
          dockerfile: /github/workspace/docker/cron/Dockerfile
          tag_with_ref: false
          tags: tasks
      - name: build main docker image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: openstates/openstates.org
          dockerfile: /github/workspace/docker/uwsgi/Dockerfile
          tag_with_ref: true
          tags: latest, django-dev
    runs-on: ubuntu-latest
